### ISSUE TITLE
[Refactor] 팀/아티스트 로직 수정

### ISSUE THREAD

**Issue by greedyBackEnd** [Happi-Cat-Tiger/Happi-Day-Back#133]
## 🚩 이슈 요약
- 팀/아티스트 로직 수정

## 🚧 TO-DO
 - [x] 유저가 팀/아티스트를 조회하는 시나리오 수정
 - [x] 유저가 팀/아티스트를 구독하는 시나리오 수정
 - [x] 한 페이지에서 구독 중인 팀/아티스트와 새롭게 추가할 아티스트를 조회할 수 있도록 수정 예정

## 🍀 추가 확인 사항  
 - 무한 스크롤을 쓸 건데  selectAll로 날려도 되는지?
