### ISSUE TITLE
[Feature] 이벤트 게시글 목록 필터링 조회 

### ISSUE THREAD

**Issue by yonzn0213** [Happi-Cat-Tiger/Happi-Day-Back#151]
## 🚩 이슈 요약
- 이벤트 게시글 목록 필터링 조회

## 🚧 TO-DO
 - [ ] 이벤트 상태 컬럼 추가
 - [ ] 내가 구독한 아티스트/팀만 조회
 - [ ] 진행 중인 이벤트만 조회
