### ISSUE TITLE
[Feature] 유저 기능 추가

### ISSUE THREAD

**Issue by sy-k-98** [Happi-Cat-Tiger/Happi-Day-Back#155]
## 🚩 이슈 요약
- 유저 기능 추가

## 🚧 TO-DO
 - [ ] 회원 가입 시, 약관 동의 여부/ 날짜 저장
 - [ ] 회원 탈퇴 시, 비밀번호 입력하고 본인 인증해야 탈퇴 가능
 - [ ] 프로필 사진 업로드

## 🍀 추가 확인 사항  
 - 확인해야할 사항
