### ISSUE TITLE
[Feature] 기본 이미지 유틸 로직 추가

### ISSUE THREAD

**Issue by greedyBackEnd** [Happi-Cat-Tiger/Happi-Day-Back#167]
## 🚩 이슈 요약
- 기본 이미지 유틸 로직 추가

## 🚧 TO-DO
 - [ ] 기본 이미지가 필요한 곳에 사용할 수 있도록 로직 추가
 - [ ] 카드형 게시글 썸네일, 이벤트 썸네일, 굿즈 썸네일, 유저 프로필, 팀/아티스트 프로필
 - [ ] db seeder에서 기본 이미지를 가지도록 수정
 - [ ] 팀/아티스트 등록 시, 이미지가 없다면  기본 이미지를 가지도록 수정

## 🍀 추가 확인 사항  
 -
