### ISSUE TITLE
[refactor] 굿즈/공구, 게시글 기타 기능 수정, 엔티티 승격

### ISSUE THREAD

**Issue by csumin0825** [Happi-Cat-Tiger/Happi-Day-Back#190]
## 🚩 이슈 요약
- 굿즈/공구 기타 기능 수정
- 게시글 기타 기능 수정
- Entity 승격

## 🚧 TO-DO
 - [x] 주문조회 response 수정
 - [ ] 해시태그 기능 수정
 - [x] 판매글 필터링 조회 기능 수정
 - [x] 판매글 기타 기능 수정
 - [x] 게시글 필터링 조회 기능 수정
 - [x] 엔티티 승격 (판매글 찜하기, 게시글 좋아요, 게시글 해시태그)

## 🍀 추가 확인 사항  
 - 확인해야할 사항
